{% set name = "cuda-cuobjdump" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "97375baa5456aba6fd55385d7303acf887bfda0597d8e88c6b5c0db43fb7ee1e" %}  # [linux64]
{% set sha256 = "21974630c974aabe9573c4f091d39acaef52f8e0cfd6ed599e56883fe2e0d879" %}  # [aarch64]
{% set sha256 = "9d1aeb5a25ea4be1abb9ae34985ce9734332d686c314ce597b45d79967286a42" %}  # [win64]
{% set sha256 = "2df6140a0cde3c33a71c8b065e0adbbee21c2b3f6d5cbc2f5128ab0493654a4c" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/{{ platform }}/cuda_cuobjdump-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cuobjdump                     # [linux]
    - bash test-rpath.sh                                # [linux]
    - if not exist %LIBRARY_BIN%\\cuobjdump.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Extracts information from CUDA binary files
  description: |
    Extracts information from CUDA binary files and presents them in human
    readable format.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
