{% set name = "cuda-cuobjdump" %}
{% set version = "13.4.92" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "6c2e30eaacb8038bd3539c40ebc09427f4678a29b0ab03cb13fa48acaad53dd8" %}  # [linux64]
{% set sha256 = "7f04e612ff62539aff20b84369283da3c9f9e618fd5114bddd46ba90ca6e61ab" %}  # [aarch64]
{% set sha256 = "ce9b95893719e0b070c6abef2ed90fb2438cfbc4f44e561cd72c933b839c616d" %}  # [win64]
{% set sha256 = "1ba90fbd6f230121693a81cb49876df7ae28efb93abc27b295dc384d53f6054b" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/{{ platform }}/cuda_cuobjdump-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cuobjdump                     # [linux]
    - bash test-rpath.sh                                # [linux]
    - if not exist %LIBRARY_BIN%\\cuobjdump.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Extracts information from CUDA binary files
  description: |
    Extracts information from CUDA binary files and presents them in human
    readable format.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
