{% set name = "cuda-cuobjdump" %}
{% set version = "13.2.78" %}
{% set cuda_version = "13.2" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/{{ platform }}/cuda_cuobjdump-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 85541582eb4689e3012627913468ab14fda6676ee95e01b0247e5bd6a174dc61  # [linux64]
  sha256: b0414bc750bd5087fa80020e208a0d72e76bfe0eeb201e3d46721fb4f783bda0  # [aarch64]
  sha256: f41fd7ecb9de9db155a56aaf47d93ae407b73684ec434edd17c2637ddef9563e  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cuobjdump                     # [linux]
    - bash test-rpath.sh                                # [linux]
    - if not exist %LIBRARY_BIN%\\cuobjdump.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Extracts information from CUDA binary files
  description: |
    Extracts information from CUDA binary files and presents them in human
    readable format.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
